name: CI

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Windows, python: '3.10', os: windows-latest}
          - {name: Mac, python: '3.10', os: macos-latest}
          - {name: 'Ubuntu', python: '3.10', os: ubuntu-latest}
          - {name: '3.11', python: '3.11.0-rc.2 - 3.11', os: ubuntu-latest}
          - {name: '3.9', python: '3.9', os: ubuntu-latest}
          - {name: '3.8', python: '3.8', os: ubuntu-latest}
          - {name: '3.7', python: '3.7', os: ubuntu-latest}
          - {name: '3.6', python: '3.6', os: ubuntu-latest}
          - {name: '3.5', python: '3.5', os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          git submodule update --init
          python -m pip install -e .["test"]

      - name: Run pre-commit
        if: ${{ matrix.name == 'Ubuntu' }}
        run: |
          python -m pip install pre-commit
          pre-commit run --all-files

      - name: Run Tests
        run: |
          python -m pytest --cov vtzero --cov-report xml --cov-report term-missing

      - name: Upload Results
        if: ${{ matrix.name == 'Ubuntu' }}
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: ${{ matrix.python }}
          fail_ci_if_error: false
